### ISSUE TITLE
Use tapables AsyncHooks instead of SyncHook

### ISSUE THREAD

**Issue by MurmeltierS** [unshopable/melter#4]
### What type of change do you want to see?

New feature

### Overview

Find fitting AsyncHooks for each use case (AsyncParallelHook, AsyncParallelBailHook, AsyncSeriesHook, AsyncSeriesBailHook, AsyncSeriesWaterfallHook) and switch over from SyncHooks.
 
 This should be backwards comaptible as AsyncHooks also expose an `tap()` method.
 

### Motivation

We are trying to implement a Plugin that requires to call an external library only available as an async API.

**Comment by algora-pbc** [comment]
💎 **$20** bounty created by @MurmeltierS
👉 To claim this bounty, [submit your pull request on Algora](https://console.algora.io/bounties/cllo344ii0002mj0fcib6co0l)
📝 Before proceeding, please make sure you can [**receive payouts**](https://docs.algora.io/bounties/payments#country-support) in your country
💵 Payment arrives in your account 2-5 days after the bounty is rewarded
💯 You keep 100% of the bounty award
🙏 Thank you for contributing to unshopable/melter!
